name: released release test

on:
  release:
    types: [released]
#- published リリース、プレリリース、またはリリースのドラフトが公開されました。
#- created ドラフトが保存されたか、事前にドラフトとして保存されずにリリースまたはプレリリースが公開されました。
#- released リリースが公開されたか、プレリリースがリリースに変更されました。
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'released release test'