name: tag create test

on:
  create:
    tags:
      - 'release_20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]_**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'tag create test'