name: tag push test

on:
  push:
    tags:
      - 'release_20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]_**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'tag push test'